[project]
name = "pip-security-worker"
version = "0.0.2"
authors = [
    { name = "Peter McDonald", email = "git@petermcdonald.co.uk" },
]
maintainers = [
    { name = "Peter McDonald", email = "git@petermcdonald.co.uk" },
]
description = "The worker for the pip-security eco-system."
keywords = ["pip", "security"]
readme = {file = "README.md", content-type = "text/markdown"}
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.13"

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
  "Programming Language :: Python :: 3.16",
  "Typing :: Typed",
]

dependencies = [
    "defusedxml>=0.7.1",
    "idna>=3.20",  # Minimum version to resolve security issue (requests dependency)
    "kafka-python>=3.0.11",
    "neo4j>=6.3.1",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
    "requests>=2.34.2",
    "sentry-sdk>=2.71.0",
    "urllib3>=2.8.0",  # Minimum version to resolve security issue (sentry-sdk dependency)
]

[project.urls]
Homepage = "https://github.com/petermcd/PIP-Security-Worker"
Documentation = "https://github.com/petermcd/PIP-Security-Worker"
Repository = "https://github.com/petermcd/PIP-Security-Worker.git"
Issues = "https://github.com/petermcd/PIP-Security-Worker/issues"

[build-system]
requires = ["setuptools>=84", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
lint = [
    "ruff>=0.16.8",
    "troml>=0.4.1",
    "ty>=0.0.82",
]
test = [
    "freezegun>=1.5.5",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.16.0",
]

[tool.pytest.ini_options]
addopts = "--cov=pip_security_worker --cov-report term-missing --cov-report xml:coverage.xml"

[tool.ruff]
line-length = 120


[project.scripts]
analyze = "pip_security_worker.cli:run_analysis"
update_advisory_db = "pip_security_worker.cli:run_update_advisory_db"
updated_packages = "pip_security_worker.cli:run_recent_updated_packages"

